version: '3.8'

services:
  nginx:
    image: "nginx:1.27.0-bookworm"
    container_name: nginx
    volumes:
      - ~/nginx/production.conf:/etc/nginx/nginx.conf
      - ~/certs:/certs
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    ports:
      - 443:443
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
      start_interval: 1s

  frontend:
    container_name: webepg_frontend
    image: ghcr.io/bacco007/webepg/webepg-frontend:main
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - proxy
    ports:
      - "3000:3000"  # Expose frontend port internally to the network
    depends_on:
      - backend

  backend:
    container_name: webepg_backend
    image: ghcr.io/bacco007/webepg/webepg-backend:main
    restart: always
    networks:
      - proxy
    ports:
      - "8000:8000"  # Expose backend port internally to the network
    volumes:
      - ~/xmltvdata:/app/xmltvdata/remote

networks:
  proxy:
    external: true
    name: proxy
