export const XMLTV_NET_SOURCES = [
  {
    id: 'local',
    group: 'Local',
    location: 'Local XMLTV File',
    url: 'localfile',
  },
  {
    id: 'xmltvnet-adelaide',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'Adelaide',
    url: 'http://xmltv.net/xml_files/Adelaide.xml',
  },
  {
    id: 'xmltvnet-albany',
    group: 'xmltv.net',
    subgroup: 'WA',
    location: 'Albany',
    url: 'http://xmltv.net/xml_files/Albany.xml',
  },
  {
    id: 'xmltvnet-albury-wodonga',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Albury / Wodonga',
    url: 'http://xmltv.net/xml_files/Albury_Wodonga.xml',
  },
  {
    id: 'xmltvnet-ballarat',
    group: 'xmltv.net',
    subgroup: 'VIC',
    location: 'Ballarat',
    url: 'http://xmltv.net/xml_files/Ballarat.xml',
  },
  {
    id: 'xmltvnet-bendigo',
    group: 'xmltv.net',
    subgroup: 'VIC',
    location: 'Bendigo',
    url: 'http://xmltv.net/xml_files/Bendigo.xml',
  },
  {
    id: 'xmltvnet-brisbane',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'Brisbane',
    url: 'http://xmltv.net/xml_files/Brisbane.xml',
  },
  {
    id: 'xmltvnet-broken-hill',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Broken Hill',
    url: 'http://xmltv.net/xml_files/Broken_Hill.xml',
  },
  {
    id: 'xmltvnet-bunbury',
    group: 'xmltv.net',
    subgroup: 'WA',
    location: 'Bunbury',
    url: 'http://xmltv.net/xml_files/Bunbury.xml',
  },
  {
    id: 'xmltvnet-cairns',
    group: 'xmltv.net',
    location: 'Cairns',
    url: 'http://xmltv.net/xml_files/Cairns.xml',
  },
  {
    id: 'xmltvnet-canberra',
    group: 'xmltv.net',
    location: 'Canberra',
    url: 'http://xmltv.net/xml_files/Canberra.xml',
  },
  {
    id: 'xmltvnet-central-coast-nsw',
    group: 'xmltv.net',
    location: 'Central Coast NSW',
    url: 'http://xmltv.net/xml_files/Central_Coast.xml',
  },
  {
    id: 'xmltvnet-coffs-harbour',
    group: 'xmltv.net',
    location: 'Coffs Harbour',
    url: 'http://xmltv.net/xml_files/Coffs_Harbour.xml',
  },
  {
    id: 'xmltvnet-darwin',
    group: 'xmltv.net',
    location: 'Darwin',
    url: 'http://xmltv.net/xml_files/Darwin.xml',
  },
  {
    id: 'xmltvnet-geelong',
    group: 'xmltv.net',
    location: 'Geelong',
    url: 'http://xmltv.net/xml_files/Geelong.xml',
  },
  {
    id: 'xmltvnet-gippsland',
    group: 'xmltv.net',
    location: 'Gippsland',
    url: 'http://xmltv.net/xml_files/Gippsland.xml',
  },
  {
    id: 'xmltvnet-gold-coast',
    group: 'xmltv.net',
    location: 'Gold Coast',
    url: 'http://xmltv.net/xml_files/Goldcoast.xml',
  },
  {
    id: 'xmltvnet-griffith',
    group: 'xmltv.net',
    location: 'Griffith',
    url: 'http://xmltv.net/xml_files/Griffith.xml',
  },
  {
    id: 'xmltvnet-hobart',
    group: 'xmltv.net',
    location: 'Hobart',
    url: 'http://xmltv.net/xml_files/Hobart.xml',
  },
  {
    id: 'xmltvnet-jurien-bay',
    group: 'xmltv.net',
    location: 'Jurien Bay',
    url: 'http://xmltv.net/xml_files/Jurien_Bay.xml',
  },
  {
    id: 'xmltvnet-launceston',
    group: 'xmltv.net',
    location: 'Launceston',
    url: 'http://xmltv.net/xml_files/Launceston.xml',
  },
  {
    id: 'xmltvnet-lismore',
    group: 'xmltv.net',
    location: 'Lismore',
    url: 'http://xmltv.net/xml_files/Lismore.xml',
  },
  {
    id: 'xmltvnet-mackay',
    group: 'xmltv.net',
    location: 'Mackay',
    url: 'http://xmltv.net/xml_files/Mackay.xml',
  },
  {
    id: 'xmltvnet-mandurah',
    location: 'Mandurah',
    url: 'http://xmltv.net/xml_files/Mandurah.xml',
  },
  {
    id: 'xmltvnet-melbourne',
    location: 'Melbourne',
    url: 'http://xmltv.net/xml_files/Melbourne.xml',
  },
  {
    id: 'xmltvnet-mildura-sunraysia',
    group: 'xmltv.net',
    location: 'Mildura/Sunraysia',
    url: 'http://xmltv.net/xml_files/Mildura_Sunraysia.xml',
  },
  {
    id: 'xmltvnet-newcastle',
    group: 'xmltv.net',
    location: 'Newcastle',
    url: 'http://xmltv.net/xml_files/Newcastle.xml',
  },
  {
    id: 'xmltvnet-nsw-regional',
    group: 'xmltv.net',
    location: 'NSW Regional',
    url: 'http://xmltv.net/xml_files/Remote_Central.xml',
  },
  {
    id: 'xmltvnet-nt-regional',
    group: 'xmltv.net',
    location: 'NT Regional',
    url: 'http://xmltv.net/xml_files/NT_Regional.xml',
  },
  {
    id: 'xmltvnet-orange',
    group: 'xmltv.net',
    location: 'Orange',
    url: 'http://xmltv.net/xml_files/Orange_Dubbo.xml',
  },
  {
    id: 'xmltvnet-perth',
    group: 'xmltv.net',
    location: 'Perth',
    url: 'http://xmltv.net/xml_files/Perth.xml',
  },
  {
    id: 'xmltvnet-port-augusta',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'Port Augusta',
    url: 'http://xmltv.net/xml_files/Port_Augusta.xml',
  },
  {
    id: 'xmltvnet-renmark',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'Renmark',
    url: 'http://xmltv.net/xml_files/Renmark.xml',
  },
  {
    id: 'xmltvnet-riverland',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'Riverland',
    url: 'http://xmltv.net/xml_files/Riverland.xml',
  },
  {
    id: 'xmltvnet-qld-regional',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'QLD Regional',
    url: 'http://xmltv.net/xml_files/QLD_Regional.xml',
  },
  {
    id: 'xmltvnet-rockhampton',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'Rockhampton',
    url: 'http://xmltv.net/xml_files/Rockhampton.xml',
  },
  {
    id: 'xmltvnet-sa-regional',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'S.A. Regional',
    url: 'http://xmltv.net/xml_files/SA_Regional.xml',
  },
  {
    id: 'xmltvnet-shepparton',
    location: 'Shepparton',
    group: 'xmltv.net',
    subgroup: 'VIC',
    url: 'http://xmltv.net/xml_files/Shepparton.xml',
  },
  {
    id: 'xmltvnet-south-coast-nsw',
    group: 'xmltv.net',
    location: 'South Coast NSW',
    url: 'http://xmltv.net/xml_files/South_Coast.xml',
  },
  {
    id: 'xmltvnet-south-east-sa',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'South East S.A.',
    url: 'http://xmltv.net/xml_files/South_East_SA.xml',
  },
  {
    id: 'xmltvnet-spencer-gulf',
    group: 'xmltv.net',
    subgroup: 'SA',
    location: 'Spencer Gulf',
    url: 'http://xmltv.net/xml_files/Spencer_Gulf.xml',
  },
  {
    id: 'xmltvnet-sunshine-coast',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'Sunshine Coast',
    url: 'http://xmltv.net/xml_files/Sunshine_Coast.xml',
  },
  {
    id: 'xmltvnet-sydney',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Sydney',
    url: 'http://xmltv.net/xml_files/Sydney.xml',
  },
  {
    id: 'xmltvnet-tamworth',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Tamworth',
    url: 'http://xmltv.net/xml_files/Tamworth.xml',
  },
  {
    id: 'xmltvnet-taree-port-macquarie',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Taree / Port Macquarie',
    url: 'http://xmltv.net/xml_files/Taree_Port_Macquarie.xml',
  },
  {
    id: 'xmltvnet-tasmania-regional',
    group: 'xmltv.net',
    subgroup: 'Tas',
    location: 'Tasmania Regional',
    url: 'http://xmltv.net/xml_files/TAS_Regional.xml',
  },
  {
    id: 'xmltvnet-toowoomba',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'Toowoomba',
    url: 'http://xmltv.net/xml_files/Toowoomba.xml',
  },
  {
    id: 'xmltvnet-townsville',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'Townsville',
    url: 'http://xmltv.net/xml_files/Townsville.xml',
  },
  {
    id: 'xmltvnet-wa-regional',
    group: 'xmltv.net',
    subgroup: 'WA',
    location: 'W.A. Regional',
    url: 'http://xmltv.net/xml_files/WA_Regional.xml',
  },
  {
    id: 'xmltvnet-wagga-wagga',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Wagga Wagga',
    url: 'http://xmltv.net/xml_files/Wagga_Wagga.xml',
  },
  {
    id: 'xmltvnet-wide-bay',
    group: 'xmltv.net',
    subgroup: 'QLD',
    location: 'Wide Bay',
    url: 'http://xmltv.net/xml_files/Wide_Bay.xml',
  },
  {
    id: 'xmltvnet-wollongong',
    group: 'xmltv.net',
    subgroup: 'NSW',
    location: 'Wollongong',
    url: 'http://xmltv.net/xml_files/Wollongong.xml',
  },
  {
    id: 'mjh-binge',
    group: 'mjh.nz',
    subgroup: 'Subscription',
    location: 'Binge',
    url: 'https://i.mjh.nz/Binge/epg.xml.gz',
  },
  {
    id: 'mjh-kayo',
    group: 'mjh.nz',
    subgroup: 'Subscription',
    location: 'Kayo',
    url: 'https://i.mjh.nz/Kayo/epg.xml.gz',
  },
  {
    id: 'mjh-flash',
    group: 'mjh.nz',
    subgroup: 'Subscription',
    location: 'Flash',
    url: 'https://i.mjh.nz/Flash/epg.xml.gz',
  },
  {
    id: 'mjh-foxtel',
    group: 'mjh.nz',
    subgroup: 'Subscription',
    location: 'Foxtel',
    url: 'https://i.mjh.nz/Foxtel/epg.xml.gz',
  },
  {
    id: 'mjh-optus',
    group: 'mjh.nz',
    subgroup: 'Subscription',
    location: 'Optus Sport',
    url: 'https://i.mjh.nz/Optus/epg.xml.gz',
  },
  {
    id: 'mjh-nz',
    group: 'mjh.nz',
    subgroup: 'FTA',
    location: 'New Zealand',
    url: 'https://i.mjh.nz/nz/epg.xml.gz',
  },
  {
    id: 'mjh-skysportnownz',
    group: 'mjh.nz',
    subgroup: 'Subscription',
    location: 'Sky Sport Now (NZ)',
    url: 'https://i.mjh.nz/SkySportNow/epg.xml.gz',
  },
  {
    id: 'mjh-auall',
    group: 'mjh.nz',
    subgroup: 'FTA',
    location: 'Australia - All',
    url: 'https://i.mjh.nz/au/all/epg.xml.gz',
  },
  {
    id: 'dp247-freeviewuk',
    group: 'United Kingdom',
    location: 'Freeview (dp247)',
    url: 'https://raw.githubusercontent.com/dp247/Freeview-EPG/master/epg.xml',
  },
  {
    id: 'test_watvvideos',
    group: 'Testing',
    location: 'Perth (Test)',
    url: 'https://www.xmlepg.net/clients/02/ftaper.xml',
  },
];
