CLEANUP_LIST = [
    "Western Australia",
    "WA",
    "Victoria, Regional",
    "Victoria, Gippsland",
    "Victoria, Albury",
    "Victoria",
    "VIC",
    "Tasmania",
    "TAS",
    "Sydney",
    "Southern Cross",
    "Southern, Wollongong",
    "Southern, Wagga Wagga",
    "Wagga",
    "Wagga Wagga",
    "Southern, South Coast",
    "Southern, Orange",
    "Southern, Canberra",
    "South East SA",
    "South East",
    "South Australia",
    "Shepparton",
    "SA",
    "Riverland",
    "Queensland, Wide Bay",
    "Queensland, Townsville",
    "Queensland, Sunshine Coast",
    "Queensland, Rockhampton",
    "Queensland, Mackay",
    "Queensland, Cairns",
    "Queensland",
    "QLD, Toowoomba",
    "QLD",
    "Prime",
    "Perth",
    "NT",
    "NSW/Vic",
    "NSW",
    "Northern, Tamworth/Taree/Port Macquarie",
    "Northern, Newcastle",
    "Northern, Lismore/Coffs Harbour",
    "Northern Territory",
    "Northern NSW",
    "Mildura",
    "Melbourne",
    "Mackay",
    "Griffith",
    "Gold Coast",
    "Eastern",
    "DDT",
    "Darwin",
    "Central",
    "Central Qld",
    "Broken Hill",
    "Brisbane",
    "Albury",
    "Adelaide",
    "ACT",
]

# Dictionary of channel groups and their associated channels
CHANNEL_GROUPS = {
    "Seven": ["7", "7TWO", "7mate", "7Bravo"],
    "Nine": ["9", "9Gem", "9Go!", "9Life"],
    "Ten": ["10", "10 Bold", "10 Peach", "10 Shake"],
    "ABC": ["ABC", "ABC Kids", "ABC ME", "ABC News"],
    "SBS": ["SBS", "SBS Viceland", "SBS Food", "SBS World Movies"],
}
