CLEANUP_LIST = [
    "Western Australia",
    "WA",
    "Victoria, Regional",
    "Victoria, Gippsland",
    "Victoria, Albury",
    "Victoria",
    "VIC",
    "Tasmania",
    "TAS",
    "Sydney",
    "Southern Cross",
    "Southern, Wollongong",
    "Southern, Wagga Wagga",
    "Wagga",
    "Wagga Wagga",
    "Southern, South Coast",
    "Southern, Orange",
    "Southern, Canberra",
    "South East SA",
    "South East",
    "South Australia",
    "Shepparton",
    "SA",
    "Riverland",
    "Queensland, Wide Bay",
    "Queensland, Townsville",
    "Queensland, Sunshine Coast",
    "Queensland, Rockhampton",
    "Queensland, Mackay",
    "Queensland, Cairns",
    "Queensland",
    "QLD, Toowoomba",
    "QLD",
    "Prime",
    "Perth",
    "NT",
    "NSW/Vic",
    "NSW",
    "Northern, Tamworth/Taree/Port Macquarie",
    "Northern, Newcastle",
    "Northern, Lismore/Coffs Harbour",
    "Northern Territory",
    "Northern NSW",
    "Northern",
    "Mildura",
    "Melbourne",
    "Mackay",
    "Griffith",
    "Gold Coast",
    "Eastern",
    "DDT",
    "Darwin",
    "Central",
    "Central Qld",
    "Broken Hill",
    "Brisbane",
    "Albury",
    "Adelaide",
    "ACT",
]

# Dictionary of channel groups and their associated channels
CHANNEL_GROUPS = {
    "Seven": [
        "7",
        "7Bravo",
        "7HD",
        "7TWO",
        "7TWO HD",
        "7flix",
        "7mate",
        "7mate HD",
        "RACING.COM",
        "TVSN",
    ],
    "Nine": [
        "9",
        "9GEM",
        "9GEM HD",
        "9GO!",
        "9Gem",
        "9Gem HD",
        "9Go!",
        "9Go! HD",
        "9HD",
        "9Life",
        "9Rush",
        "Imparja",
    ],
    "Ten": [
        "10",
        "10 BOLD Drama",
        "10 HD",
        "10 Peach Comedy",
        "10HD",
        "Nickelodeon",
        "you.tv",
        "gecko",
        "Sky News Regional",
    ],
    "ABC": [
        "ABC Entertains",
        "ABC Jazz",
        "ABC Kids/ABC Family",
        "ABC NEWS",
        "ABC TV",
        "ABC TV HD",
        "Double J",
    ],
    "SBS": [
        "SBS",
        "SBS Food",
        "SBS HD",
        "SBS Radio 1",
        "SBS Radio 2",
        "SBS VICELAND HD",
        "SBS World Movies",
        "SBS World Watch",
        "NITV",
        "NITV HD",
    ],
}
