name: PR Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate PR title format
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          scopes: |
            frontend
            backend
            docker
            config
            docs
          requireScope: false

      - name: Check PR description
        uses: actions-cool/pr-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          description-regexp: '## Description.*'

      - name: Ensure PR is not WIP
        if: contains(github.head_ref, 'wip') || contains(github.head_ref, 'WIP')
        run: |
          echo "Error: Work in progress branches should not be merged"
          exit 1

